- tinytag/tinytag.py
As discussed in issue #24 - here are the changes I made.
> Parse disc number and total number of discs from OGG, FLAC, MP3 and WMA

- tinytag/tinytag.py
Pull requesting again without the tests in the case you reconsidered #27
> Add albumartist.

- setup.py
small change in the setup, because you already updated the LICENSE of the project. 
Also when can we expect version 0.19.0 on pypi.. 🙂
> Updated license to MIT

- README.md
> Fix small typo: stabiity -> stability

- tinytag/tinytag.py
As far as I can tell, the current implementation supports these file extensions.
> Extend list of supported file extensions

- tinytag/tinytag.py
Minor performance improvement.
> Don't use regex when parsing genre

- README.md
- tinytag/tinytag.py
> Add .m4v to list of supported file extensions

- tinytag/__init__.py
My previous flake8 PR introduced breaking API changes, which was not intended.
> __init__.py: Restore imports

- setup.cfg
> Fix deprecations related to setuptools

- tinytag/tinytag.py
> Add list of supported file extensions

- LICENSE
- tinytag/tinytag.py
@devsnd if you're fine with this change
> Add myself to copyright notices

- .github/workflows/tests.yml
- release.py
- setup.cfg
- setup.py
- tinytag/__init__.py
- tinytag/__main__.py
- tinytag/tests/test_all.py
- tinytag/tests/test_cli.py
- tinytag/tinytag.py
> Use Pylint for linting

- .github/workflows/tests.yml
- README.md
- release.py
- setup.cfg
- tinytag/__main__.py
- tinytag/tests/test_all.py
- tinytag/tests/test_cli.py
- tinytag/tinytag.py
> Add type hints to codebase

- README.md
- tinytag/__init__.py
- tinytag/tests/test_all.py
- tinytag/tinytag.py
> Provide access to all available images

- pyproject.toml
- tinytag/tinytag.py
It's overkill, and this is the only case it's used.
> Stop using regex module

- tinytag/tests/test_all.py
- tinytag/tinytag.py
- Avoid some small reads/seeks on file handles
- Avoid some unnecessary unpacking of values
- Remove unnecessary BytesIO streams
- Various cleanups
> Avoid unnecessary work when unpacking values

- .github/workflows/tests.yml
- pyproject.toml
- tinytag/__main__.py
- tinytag/tests/test_all.py
- tinytag/tests/test_cli.py
- tinytag/tinytag.py
In order to ensure compatibility with as many style checkers as possible out of the box.
> Limit line length to 79 characters

- tinytag/tinytag.py
It's redundant, and we don't use this pattern for other formats.
> MP4: remove nested Parser class

- tinytag/tinytag.py
Until someone shows up with audio files that actually use these value types, remove support for them. I haven't seen them used in the wild, and we have no sample files for our test suite.
> Remove support for unpacking unused value types

- tinytag/tests/test_all.py
- tinytag/tinytag.py
And take pre-skip into account when calculating the duration.
Fixes #237
> Opus: calculate audio bitrate

- pyproject.toml
- tinytag/tests/test_all.py
- tinytag/tinytag.py
Fixes some errors reported by the Pyright type checker.
> Improve a few incomplete type hints

- .github/workflows/tests.yml
- pyproject.toml
We should aim to support multiple static type checkers.
> CI: Add Pyright static type checking
